// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0--rc2
// source: user.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetUserByIdClient is the client API for GetUserById service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetUserByIdClient interface {
	GetUserById(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type getUserByIdClient struct {
	cc grpc.ClientConnInterface
}

func NewGetUserByIdClient(cc grpc.ClientConnInterface) GetUserByIdClient {
	return &getUserByIdClient{cc}
}

func (c *getUserByIdClient) GetUserById(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/getUserById/getUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserByIdServer is the server API for GetUserById service.
// All implementations must embed UnimplementedGetUserByIdServer
// for forward compatibility
type GetUserByIdServer interface {
	GetUserById(context.Context, *UserRequest) (*UserResponse, error)
	mustEmbedUnimplementedGetUserByIdServer()
}

// UnimplementedGetUserByIdServer must be embedded to have forward compatible implementations.
type UnimplementedGetUserByIdServer struct {
}

func (UnimplementedGetUserByIdServer) GetUserById(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (UnimplementedGetUserByIdServer) mustEmbedUnimplementedGetUserByIdServer() {}

// UnsafeGetUserByIdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetUserByIdServer will
// result in compilation errors.
type UnsafeGetUserByIdServer interface {
	mustEmbedUnimplementedGetUserByIdServer()
}

func RegisterGetUserByIdServer(s grpc.ServiceRegistrar, srv GetUserByIdServer) {
	s.RegisterService(&GetUserById_ServiceDesc, srv)
}

func _GetUserById_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserByIdServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/getUserById/getUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserByIdServer).GetUserById(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetUserById_ServiceDesc is the grpc.ServiceDesc for GetUserById service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetUserById_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "getUserById",
	HandlerType: (*GetUserByIdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getUserById",
			Handler:    _GetUserById_GetUserById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
